apiVersion: v1
kind: Namespace
metadata:
  name: keti
  labels:
    name: keti
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insight-scope
  namespace: keti
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insight-scope
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: insight-scope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: insight-scope
subjects:
  - kind: ServiceAccount
    name: insight-scope
    namespace: keti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-scope
  namespace: keti
  labels:
    app: insight-scope
    component: keti-apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insight-scope
  template:
    metadata:
      labels:
        app: insight-scope
        component: keti-apollo
    spec:
      serviceAccountName: insight-scope
      containers:
        - name: insight-scope
          image: ketidevit2/insight-scope:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
              name: http
          env:
            - name: HTTP_PORT
              value: "9092"
            - name: GRPC_PORT
              value: "50054"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /ready
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: insight-scope
  namespace: keti
  labels:
    app: insight-scope
spec:
  selector:
    app: insight-scope
  ports:
    - name: http
      port: 9092
      targetPort: 9092
  type: ClusterIP
