// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: scope.proto

package scopepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InsightScopeService_AnalyzePod_FullMethodName                = "/insight.scope.v1.InsightScopeService/AnalyzePod"
	InsightScopeService_GetCachedAnalysis_FullMethodName         = "/insight.scope.v1.InsightScopeService/GetCachedAnalysis"
	InsightScopeService_AnalyzeNamespace_FullMethodName          = "/insight.scope.v1.InsightScopeService/AnalyzeNamespace"
	InsightScopeService_GetModelProfile_FullMethodName           = "/insight.scope.v1.InsightScopeService/GetModelProfile"
	InsightScopeService_SearchModels_FullMethodName              = "/insight.scope.v1.InsightScopeService/SearchModels"
	InsightScopeService_ListAllModels_FullMethodName             = "/insight.scope.v1.InsightScopeService/ListAllModels"
	InsightScopeService_GetStorageRecommendation_FullMethodName  = "/insight.scope.v1.InsightScopeService/GetStorageRecommendation"
	InsightScopeService_GetCategoryRecommendation_FullMethodName = "/insight.scope.v1.InsightScopeService/GetCategoryRecommendation"
	InsightScopeService_StreamAnalysisResults_FullMethodName     = "/insight.scope.v1.InsightScopeService/StreamAnalysisResults"
	InsightScopeService_HealthCheck_FullMethodName               = "/insight.scope.v1.InsightScopeService/HealthCheck"
)

// InsightScopeServiceClient is the client API for InsightScopeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InsightScopeServiceClient interface {
	// Pod 분석 요청 (YAML 또는 기존 Pod)
	AnalyzePod(ctx context.Context, in *AnalyzePodRequest, opts ...grpc.CallOption) (*AnalyzePodResponse, error)
	// 캐시된 분석 결과 조회
	GetCachedAnalysis(ctx context.Context, in *GetCachedAnalysisRequest, opts ...grpc.CallOption) (*AnalyzePodResponse, error)
	// 네임스페이스의 모든 Pod 분석
	AnalyzeNamespace(ctx context.Context, in *AnalyzeNamespaceRequest, opts ...grpc.CallOption) (*AnalyzeNamespaceResponse, error)
	// AI 모델 프로필 조회
	GetModelProfile(ctx context.Context, in *GetModelProfileRequest, opts ...grpc.CallOption) (*ModelProfileResponse, error)
	// 모델 검색
	SearchModels(ctx context.Context, in *SearchModelsRequest, opts ...grpc.CallOption) (*SearchModelsResponse, error)
	// 모든 모델 목록
	ListAllModels(ctx context.Context, in *ListAllModelsRequest, opts ...grpc.CallOption) (*ListAllModelsResponse, error)
	// 스토리지 추천 (모델 타입 기반)
	GetStorageRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*StorageRecommendationResponse, error)
	// 카테고리별 스토리지 추천
	GetCategoryRecommendation(ctx context.Context, in *GetCategoryRecommendationRequest, opts ...grpc.CallOption) (*StorageRecommendationResponse, error)
	// 분석 결과 스트림 (새 분석 결과 구독)
	StreamAnalysisResults(ctx context.Context, in *StreamAnalysisRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyzePodResponse], error)
	// 헬스 체크
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type insightScopeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsightScopeServiceClient(cc grpc.ClientConnInterface) InsightScopeServiceClient {
	return &insightScopeServiceClient{cc}
}

func (c *insightScopeServiceClient) AnalyzePod(ctx context.Context, in *AnalyzePodRequest, opts ...grpc.CallOption) (*AnalyzePodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzePodResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_AnalyzePod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) GetCachedAnalysis(ctx context.Context, in *GetCachedAnalysisRequest, opts ...grpc.CallOption) (*AnalyzePodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzePodResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_GetCachedAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) AnalyzeNamespace(ctx context.Context, in *AnalyzeNamespaceRequest, opts ...grpc.CallOption) (*AnalyzeNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeNamespaceResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_AnalyzeNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) GetModelProfile(ctx context.Context, in *GetModelProfileRequest, opts ...grpc.CallOption) (*ModelProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelProfileResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_GetModelProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) SearchModels(ctx context.Context, in *SearchModelsRequest, opts ...grpc.CallOption) (*SearchModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchModelsResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_SearchModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) ListAllModels(ctx context.Context, in *ListAllModelsRequest, opts ...grpc.CallOption) (*ListAllModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllModelsResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_ListAllModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) GetStorageRecommendation(ctx context.Context, in *GetRecommendationRequest, opts ...grpc.CallOption) (*StorageRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageRecommendationResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_GetStorageRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) GetCategoryRecommendation(ctx context.Context, in *GetCategoryRecommendationRequest, opts ...grpc.CallOption) (*StorageRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageRecommendationResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_GetCategoryRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightScopeServiceClient) StreamAnalysisResults(ctx context.Context, in *StreamAnalysisRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyzePodResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InsightScopeService_ServiceDesc.Streams[0], InsightScopeService_StreamAnalysisResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAnalysisRequest, AnalyzePodResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightScopeService_StreamAnalysisResultsClient = grpc.ServerStreamingClient[AnalyzePodResponse]

func (c *insightScopeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, InsightScopeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsightScopeServiceServer is the server API for InsightScopeService service.
// All implementations must embed UnimplementedInsightScopeServiceServer
// for forward compatibility.
type InsightScopeServiceServer interface {
	// Pod 분석 요청 (YAML 또는 기존 Pod)
	AnalyzePod(context.Context, *AnalyzePodRequest) (*AnalyzePodResponse, error)
	// 캐시된 분석 결과 조회
	GetCachedAnalysis(context.Context, *GetCachedAnalysisRequest) (*AnalyzePodResponse, error)
	// 네임스페이스의 모든 Pod 분석
	AnalyzeNamespace(context.Context, *AnalyzeNamespaceRequest) (*AnalyzeNamespaceResponse, error)
	// AI 모델 프로필 조회
	GetModelProfile(context.Context, *GetModelProfileRequest) (*ModelProfileResponse, error)
	// 모델 검색
	SearchModels(context.Context, *SearchModelsRequest) (*SearchModelsResponse, error)
	// 모든 모델 목록
	ListAllModels(context.Context, *ListAllModelsRequest) (*ListAllModelsResponse, error)
	// 스토리지 추천 (모델 타입 기반)
	GetStorageRecommendation(context.Context, *GetRecommendationRequest) (*StorageRecommendationResponse, error)
	// 카테고리별 스토리지 추천
	GetCategoryRecommendation(context.Context, *GetCategoryRecommendationRequest) (*StorageRecommendationResponse, error)
	// 분석 결과 스트림 (새 분석 결과 구독)
	StreamAnalysisResults(*StreamAnalysisRequest, grpc.ServerStreamingServer[AnalyzePodResponse]) error
	// 헬스 체크
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedInsightScopeServiceServer()
}

// UnimplementedInsightScopeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInsightScopeServiceServer struct{}

func (UnimplementedInsightScopeServiceServer) AnalyzePod(context.Context, *AnalyzePodRequest) (*AnalyzePodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzePod not implemented")
}
func (UnimplementedInsightScopeServiceServer) GetCachedAnalysis(context.Context, *GetCachedAnalysisRequest) (*AnalyzePodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCachedAnalysis not implemented")
}
func (UnimplementedInsightScopeServiceServer) AnalyzeNamespace(context.Context, *AnalyzeNamespaceRequest) (*AnalyzeNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeNamespace not implemented")
}
func (UnimplementedInsightScopeServiceServer) GetModelProfile(context.Context, *GetModelProfileRequest) (*ModelProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelProfile not implemented")
}
func (UnimplementedInsightScopeServiceServer) SearchModels(context.Context, *SearchModelsRequest) (*SearchModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchModels not implemented")
}
func (UnimplementedInsightScopeServiceServer) ListAllModels(context.Context, *ListAllModelsRequest) (*ListAllModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllModels not implemented")
}
func (UnimplementedInsightScopeServiceServer) GetStorageRecommendation(context.Context, *GetRecommendationRequest) (*StorageRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageRecommendation not implemented")
}
func (UnimplementedInsightScopeServiceServer) GetCategoryRecommendation(context.Context, *GetCategoryRecommendationRequest) (*StorageRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryRecommendation not implemented")
}
func (UnimplementedInsightScopeServiceServer) StreamAnalysisResults(*StreamAnalysisRequest, grpc.ServerStreamingServer[AnalyzePodResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAnalysisResults not implemented")
}
func (UnimplementedInsightScopeServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedInsightScopeServiceServer) mustEmbedUnimplementedInsightScopeServiceServer() {}
func (UnimplementedInsightScopeServiceServer) testEmbeddedByValue()                             {}

// UnsafeInsightScopeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsightScopeServiceServer will
// result in compilation errors.
type UnsafeInsightScopeServiceServer interface {
	mustEmbedUnimplementedInsightScopeServiceServer()
}

func RegisterInsightScopeServiceServer(s grpc.ServiceRegistrar, srv InsightScopeServiceServer) {
	// If the following call panics, it indicates UnimplementedInsightScopeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InsightScopeService_ServiceDesc, srv)
}

func _InsightScopeService_AnalyzePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).AnalyzePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_AnalyzePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).AnalyzePod(ctx, req.(*AnalyzePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_GetCachedAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCachedAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).GetCachedAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_GetCachedAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).GetCachedAnalysis(ctx, req.(*GetCachedAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_AnalyzeNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).AnalyzeNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_AnalyzeNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).AnalyzeNamespace(ctx, req.(*AnalyzeNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_GetModelProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).GetModelProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_GetModelProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).GetModelProfile(ctx, req.(*GetModelProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_SearchModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).SearchModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_SearchModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).SearchModels(ctx, req.(*SearchModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_ListAllModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).ListAllModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_ListAllModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).ListAllModels(ctx, req.(*ListAllModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_GetStorageRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).GetStorageRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_GetStorageRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).GetStorageRecommendation(ctx, req.(*GetRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_GetCategoryRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).GetCategoryRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_GetCategoryRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).GetCategoryRecommendation(ctx, req.(*GetCategoryRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightScopeService_StreamAnalysisResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAnalysisRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InsightScopeServiceServer).StreamAnalysisResults(m, &grpc.GenericServerStream[StreamAnalysisRequest, AnalyzePodResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InsightScopeService_StreamAnalysisResultsServer = grpc.ServerStreamingServer[AnalyzePodResponse]

func _InsightScopeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightScopeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightScopeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightScopeServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InsightScopeService_ServiceDesc is the grpc.ServiceDesc for InsightScopeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsightScopeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insight.scope.v1.InsightScopeService",
	HandlerType: (*InsightScopeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzePod",
			Handler:    _InsightScopeService_AnalyzePod_Handler,
		},
		{
			MethodName: "GetCachedAnalysis",
			Handler:    _InsightScopeService_GetCachedAnalysis_Handler,
		},
		{
			MethodName: "AnalyzeNamespace",
			Handler:    _InsightScopeService_AnalyzeNamespace_Handler,
		},
		{
			MethodName: "GetModelProfile",
			Handler:    _InsightScopeService_GetModelProfile_Handler,
		},
		{
			MethodName: "SearchModels",
			Handler:    _InsightScopeService_SearchModels_Handler,
		},
		{
			MethodName: "ListAllModels",
			Handler:    _InsightScopeService_ListAllModels_Handler,
		},
		{
			MethodName: "GetStorageRecommendation",
			Handler:    _InsightScopeService_GetStorageRecommendation_Handler,
		},
		{
			MethodName: "GetCategoryRecommendation",
			Handler:    _InsightScopeService_GetCategoryRecommendation_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _InsightScopeService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAnalysisResults",
			Handler:       _InsightScopeService_StreamAnalysisResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scope.proto",
}
