// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: forecaster.proto

package forecasterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForecastNodeRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	NodeName                string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ForecastHorizonsMinutes []int32                `protobuf:"varint,2,rep,packed,name=forecast_horizons_minutes,json=forecastHorizonsMinutes,proto3" json:"forecast_horizons_minutes,omitempty"` // e.g., [5, 10, 30, 60]
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ForecastNodeRequest) Reset() {
	*x = ForecastNodeRequest{}
	mi := &file_forecaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastNodeRequest) ProtoMessage() {}

func (x *ForecastNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastNodeRequest.ProtoReflect.Descriptor instead.
func (*ForecastNodeRequest) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{0}
}

func (x *ForecastNodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ForecastNodeRequest) GetForecastHorizonsMinutes() []int32 {
	if x != nil {
		return x.ForecastHorizonsMinutes
	}
	return nil
}

type ForecastClusterRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ForecastHorizonsMinutes []int32                `protobuf:"varint,1,rep,packed,name=forecast_horizons_minutes,json=forecastHorizonsMinutes,proto3" json:"forecast_horizons_minutes,omitempty"`
	IncludeNodeBreakdown    bool                   `protobuf:"varint,2,opt,name=include_node_breakdown,json=includeNodeBreakdown,proto3" json:"include_node_breakdown,omitempty"` // 노드별 예측 포함 여부
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ForecastClusterRequest) Reset() {
	*x = ForecastClusterRequest{}
	mi := &file_forecaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastClusterRequest) ProtoMessage() {}

func (x *ForecastClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastClusterRequest.ProtoReflect.Descriptor instead.
func (*ForecastClusterRequest) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{1}
}

func (x *ForecastClusterRequest) GetForecastHorizonsMinutes() []int32 {
	if x != nil {
		return x.ForecastHorizonsMinutes
	}
	return nil
}

func (x *ForecastClusterRequest) GetIncludeNodeBreakdown() bool {
	if x != nil {
		return x.IncludeNodeBreakdown
	}
	return false
}

type PeakIdleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeName       string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`                    // 빈 문자열이면 클러스터 전체
	LookaheadHours int32                  `protobuf:"varint,2,opt,name=lookahead_hours,json=lookaheadHours,proto3" json:"lookahead_hours,omitempty"` // 몇 시간 앞까지 예측할지
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeakIdleRequest) Reset() {
	*x = PeakIdleRequest{}
	mi := &file_forecaster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeakIdleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeakIdleRequest) ProtoMessage() {}

func (x *PeakIdleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeakIdleRequest.ProtoReflect.Descriptor instead.
func (*PeakIdleRequest) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{2}
}

func (x *PeakIdleRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PeakIdleRequest) GetLookaheadHours() int32 {
	if x != nil {
		return x.LookaheadHours
	}
	return 0
}

type SubmitHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Snapshots     []*ResourceSnapshot    `protobuf:"bytes,2,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitHistoryRequest) Reset() {
	*x = SubmitHistoryRequest{}
	mi := &file_forecaster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHistoryRequest) ProtoMessage() {}

func (x *SubmitHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHistoryRequest.ProtoReflect.Descriptor instead.
func (*SubmitHistoryRequest) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitHistoryRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SubmitHistoryRequest) GetSnapshots() []*ResourceSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type ResourceSnapshot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuUtilization       float64                `protobuf:"fixed64,2,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`                     // 0.0 ~ 1.0
	MemoryUtilization    float64                `protobuf:"fixed64,3,opt,name=memory_utilization,json=memoryUtilization,proto3" json:"memory_utilization,omitempty"`            // 0.0 ~ 1.0
	GpuUtilization       float64                `protobuf:"fixed64,4,opt,name=gpu_utilization,json=gpuUtilization,proto3" json:"gpu_utilization,omitempty"`                     // 0.0 ~ 1.0
	StorageIoUtilization float64                `protobuf:"fixed64,5,opt,name=storage_io_utilization,json=storageIoUtilization,proto3" json:"storage_io_utilization,omitempty"` // 0.0 ~ 1.0
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceSnapshot) Reset() {
	*x = ResourceSnapshot{}
	mi := &file_forecaster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSnapshot) ProtoMessage() {}

func (x *ResourceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSnapshot.ProtoReflect.Descriptor instead.
func (*ResourceSnapshot) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ResourceSnapshot) GetCpuUtilization() float64 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *ResourceSnapshot) GetMemoryUtilization() float64 {
	if x != nil {
		return x.MemoryUtilization
	}
	return 0
}

func (x *ResourceSnapshot) GetGpuUtilization() float64 {
	if x != nil {
		return x.GpuUtilization
	}
	return 0
}

func (x *ResourceSnapshot) GetStorageIoUtilization() float64 {
	if x != nil {
		return x.StorageIoUtilization
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_forecaster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{5}
}

type ForecastNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Forecasts     []*ResourceForecast    `protobuf:"bytes,2,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // 전체 예측 신뢰도
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastNodeResponse) Reset() {
	*x = ForecastNodeResponse{}
	mi := &file_forecaster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastNodeResponse) ProtoMessage() {}

func (x *ForecastNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastNodeResponse.ProtoReflect.Descriptor instead.
func (*ForecastNodeResponse) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{6}
}

func (x *ForecastNodeResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ForecastNodeResponse) GetForecasts() []*ResourceForecast {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

func (x *ForecastNodeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ResourceForecast struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	HorizonMinutes                int32                  `protobuf:"varint,1,opt,name=horizon_minutes,json=horizonMinutes,proto3" json:"horizon_minutes,omitempty"`
	PredictedCpuUtilization       float64                `protobuf:"fixed64,2,opt,name=predicted_cpu_utilization,json=predictedCpuUtilization,proto3" json:"predicted_cpu_utilization,omitempty"`
	PredictedMemoryUtilization    float64                `protobuf:"fixed64,3,opt,name=predicted_memory_utilization,json=predictedMemoryUtilization,proto3" json:"predicted_memory_utilization,omitempty"`
	PredictedGpuUtilization       float64                `protobuf:"fixed64,4,opt,name=predicted_gpu_utilization,json=predictedGpuUtilization,proto3" json:"predicted_gpu_utilization,omitempty"`
	PredictedStorageIoUtilization float64                `protobuf:"fixed64,5,opt,name=predicted_storage_io_utilization,json=predictedStorageIoUtilization,proto3" json:"predicted_storage_io_utilization,omitempty"`
	ConfidenceIntervalLower       float64                `protobuf:"fixed64,6,opt,name=confidence_interval_lower,json=confidenceIntervalLower,proto3" json:"confidence_interval_lower,omitempty"`
	ConfidenceIntervalUpper       float64                `protobuf:"fixed64,7,opt,name=confidence_interval_upper,json=confidenceIntervalUpper,proto3" json:"confidence_interval_upper,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ResourceForecast) Reset() {
	*x = ResourceForecast{}
	mi := &file_forecaster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceForecast) ProtoMessage() {}

func (x *ResourceForecast) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceForecast.ProtoReflect.Descriptor instead.
func (*ResourceForecast) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceForecast) GetHorizonMinutes() int32 {
	if x != nil {
		return x.HorizonMinutes
	}
	return 0
}

func (x *ResourceForecast) GetPredictedCpuUtilization() float64 {
	if x != nil {
		return x.PredictedCpuUtilization
	}
	return 0
}

func (x *ResourceForecast) GetPredictedMemoryUtilization() float64 {
	if x != nil {
		return x.PredictedMemoryUtilization
	}
	return 0
}

func (x *ResourceForecast) GetPredictedGpuUtilization() float64 {
	if x != nil {
		return x.PredictedGpuUtilization
	}
	return 0
}

func (x *ResourceForecast) GetPredictedStorageIoUtilization() float64 {
	if x != nil {
		return x.PredictedStorageIoUtilization
	}
	return 0
}

func (x *ResourceForecast) GetConfidenceIntervalLower() float64 {
	if x != nil {
		return x.ConfidenceIntervalLower
	}
	return 0
}

func (x *ResourceForecast) GetConfidenceIntervalUpper() float64 {
	if x != nil {
		return x.ConfidenceIntervalUpper
	}
	return 0
}

type ForecastClusterResponse struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	ClusterForecasts []*ResourceForecast            `protobuf:"bytes,1,rep,name=cluster_forecasts,json=clusterForecasts,proto3" json:"cluster_forecasts,omitempty"`                                                                  // 클러스터 평균 예측
	NodeForecasts    map[string]*NodeForecastResult `protobuf:"bytes,2,rep,name=node_forecasts,json=nodeForecasts,proto3" json:"node_forecasts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 노드별 예측 (옵션)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ForecastClusterResponse) Reset() {
	*x = ForecastClusterResponse{}
	mi := &file_forecaster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastClusterResponse) ProtoMessage() {}

func (x *ForecastClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastClusterResponse.ProtoReflect.Descriptor instead.
func (*ForecastClusterResponse) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{8}
}

func (x *ForecastClusterResponse) GetClusterForecasts() []*ResourceForecast {
	if x != nil {
		return x.ClusterForecasts
	}
	return nil
}

func (x *ForecastClusterResponse) GetNodeForecasts() map[string]*NodeForecastResult {
	if x != nil {
		return x.NodeForecasts
	}
	return nil
}

type NodeForecastResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecasts     []*ResourceForecast    `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeForecastResult) Reset() {
	*x = NodeForecastResult{}
	mi := &file_forecaster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeForecastResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeForecastResult) ProtoMessage() {}

func (x *NodeForecastResult) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeForecastResult.ProtoReflect.Descriptor instead.
func (*NodeForecastResult) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{9}
}

func (x *NodeForecastResult) GetForecasts() []*ResourceForecast {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

func (x *NodeForecastResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type PeakIdleResponse struct {
	state                  protoimpl.MessageState     `protogen:"open.v1"`
	PeakPeriods            []*PeakIdlePeriod          `protobuf:"bytes,1,rep,name=peak_periods,json=peakPeriods,proto3" json:"peak_periods,omitempty"`
	IdlePeriods            []*PeakIdlePeriod          `protobuf:"bytes,2,rep,name=idle_periods,json=idlePeriods,proto3" json:"idle_periods,omitempty"`
	RecommendedBatchWindow *BatchWindowRecommendation `protobuf:"bytes,3,opt,name=recommended_batch_window,json=recommendedBatchWindow,proto3" json:"recommended_batch_window,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeakIdleResponse) Reset() {
	*x = PeakIdleResponse{}
	mi := &file_forecaster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeakIdleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeakIdleResponse) ProtoMessage() {}

func (x *PeakIdleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeakIdleResponse.ProtoReflect.Descriptor instead.
func (*PeakIdleResponse) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{10}
}

func (x *PeakIdleResponse) GetPeakPeriods() []*PeakIdlePeriod {
	if x != nil {
		return x.PeakPeriods
	}
	return nil
}

func (x *PeakIdleResponse) GetIdlePeriods() []*PeakIdlePeriod {
	if x != nil {
		return x.IdlePeriods
	}
	return nil
}

func (x *PeakIdleResponse) GetRecommendedBatchWindow() *BatchWindowRecommendation {
	if x != nil {
		return x.RecommendedBatchWindow
	}
	return nil
}

type PeakIdlePeriod struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HorizonMinutes int32                  `protobuf:"varint,1,opt,name=horizon_minutes,json=horizonMinutes,proto3" json:"horizon_minutes,omitempty"` // 현재로부터 몇 분 후
	AvgUtilization float64                `protobuf:"fixed64,2,opt,name=avg_utilization,json=avgUtilization,proto3" json:"avg_utilization,omitempty"`
	Confidence     float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeakIdlePeriod) Reset() {
	*x = PeakIdlePeriod{}
	mi := &file_forecaster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeakIdlePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeakIdlePeriod) ProtoMessage() {}

func (x *PeakIdlePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeakIdlePeriod.ProtoReflect.Descriptor instead.
func (*PeakIdlePeriod) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{11}
}

func (x *PeakIdlePeriod) GetHorizonMinutes() int32 {
	if x != nil {
		return x.HorizonMinutes
	}
	return 0
}

func (x *PeakIdlePeriod) GetAvgUtilization() float64 {
	if x != nil {
		return x.AvgUtilization
	}
	return 0
}

func (x *PeakIdlePeriod) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type BatchWindowRecommendation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StartOffsetMinutes  int32                  `protobuf:"varint,1,opt,name=start_offset_minutes,json=startOffsetMinutes,proto3" json:"start_offset_minutes,omitempty"`   // 시작 시점 (현재로부터)
	EndOffsetMinutes    int32                  `protobuf:"varint,2,opt,name=end_offset_minutes,json=endOffsetMinutes,proto3" json:"end_offset_minutes,omitempty"`         // 종료 시점
	ExpectedUtilization float64                `protobuf:"fixed64,3,opt,name=expected_utilization,json=expectedUtilization,proto3" json:"expected_utilization,omitempty"` // 해당 시간대 예상 사용률
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchWindowRecommendation) Reset() {
	*x = BatchWindowRecommendation{}
	mi := &file_forecaster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchWindowRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWindowRecommendation) ProtoMessage() {}

func (x *BatchWindowRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWindowRecommendation.ProtoReflect.Descriptor instead.
func (*BatchWindowRecommendation) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{12}
}

func (x *BatchWindowRecommendation) GetStartOffsetMinutes() int32 {
	if x != nil {
		return x.StartOffsetMinutes
	}
	return 0
}

func (x *BatchWindowRecommendation) GetEndOffsetMinutes() int32 {
	if x != nil {
		return x.EndOffsetMinutes
	}
	return 0
}

func (x *BatchWindowRecommendation) GetExpectedUtilization() float64 {
	if x != nil {
		return x.ExpectedUtilization
	}
	return 0
}

type SubmitHistoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Accepted           bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SnapshotsProcessed int32                  `protobuf:"varint,2,opt,name=snapshots_processed,json=snapshotsProcessed,proto3" json:"snapshots_processed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitHistoryResponse) Reset() {
	*x = SubmitHistoryResponse{}
	mi := &file_forecaster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHistoryResponse) ProtoMessage() {}

func (x *SubmitHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHistoryResponse.ProtoReflect.Descriptor instead.
func (*SubmitHistoryResponse) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitHistoryResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitHistoryResponse) GetSnapshotsProcessed() int32 {
	if x != nil {
		return x.SnapshotsProcessed
	}
	return 0
}

type HealthCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Healthy          bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelReady       int32                  `protobuf:"varint,3,opt,name=model_ready,json=modelReady,proto3" json:"model_ready,omitempty"` // 0: not ready, 1: ready
	TotalPredictions int64                  `protobuf:"varint,4,opt,name=total_predictions,json=totalPredictions,proto3" json:"total_predictions,omitempty"`
	LastTrainingTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_training_time,json=lastTrainingTime,proto3" json:"last_training_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_forecaster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetModelReady() int32 {
	if x != nil {
		return x.ModelReady
	}
	return 0
}

func (x *HealthCheckResponse) GetTotalPredictions() int64 {
	if x != nil {
		return x.TotalPredictions
	}
	return 0
}

func (x *HealthCheckResponse) GetLastTrainingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTrainingTime
	}
	return nil
}

var File_forecaster_proto protoreflect.FileDescriptor

const file_forecaster_proto_rawDesc = "" +
	"\n" +
	"\x10forecaster.proto\x12\x14apollo.forecaster.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n" +
	"\x13ForecastNodeRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12:\n" +
	"\x19forecast_horizons_minutes\x18\x02 \x03(\x05R\x17forecastHorizonsMinutes\"\x8a\x01\n" +
	"\x16ForecastClusterRequest\x12:\n" +
	"\x19forecast_horizons_minutes\x18\x01 \x03(\x05R\x17forecastHorizonsMinutes\x124\n" +
	"\x16include_node_breakdown\x18\x02 \x01(\bR\x14includeNodeBreakdown\"W\n" +
	"\x0fPeakIdleRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12'\n" +
	"\x0flookahead_hours\x18\x02 \x01(\x05R\x0elookaheadHours\"y\n" +
	"\x14SubmitHistoryRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12D\n" +
	"\tsnapshots\x18\x02 \x03(\v2&.apollo.forecaster.v1.ResourceSnapshotR\tsnapshots\"\x83\x02\n" +
	"\x10ResourceSnapshot\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x0fcpu_utilization\x18\x02 \x01(\x01R\x0ecpuUtilization\x12-\n" +
	"\x12memory_utilization\x18\x03 \x01(\x01R\x11memoryUtilization\x12'\n" +
	"\x0fgpu_utilization\x18\x04 \x01(\x01R\x0egpuUtilization\x124\n" +
	"\x16storage_io_utilization\x18\x05 \x01(\x01R\x14storageIoUtilization\"\x14\n" +
	"\x12HealthCheckRequest\"\x99\x01\n" +
	"\x14ForecastNodeResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12D\n" +
	"\tforecasts\x18\x02 \x03(\v2&.apollo.forecaster.v1.ResourceForecastR\tforecasts\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"\xb6\x03\n" +
	"\x10ResourceForecast\x12'\n" +
	"\x0fhorizon_minutes\x18\x01 \x01(\x05R\x0ehorizonMinutes\x12:\n" +
	"\x19predicted_cpu_utilization\x18\x02 \x01(\x01R\x17predictedCpuUtilization\x12@\n" +
	"\x1cpredicted_memory_utilization\x18\x03 \x01(\x01R\x1apredictedMemoryUtilization\x12:\n" +
	"\x19predicted_gpu_utilization\x18\x04 \x01(\x01R\x17predictedGpuUtilization\x12G\n" +
	" predicted_storage_io_utilization\x18\x05 \x01(\x01R\x1dpredictedStorageIoUtilization\x12:\n" +
	"\x19confidence_interval_lower\x18\x06 \x01(\x01R\x17confidenceIntervalLower\x12:\n" +
	"\x19confidence_interval_upper\x18\a \x01(\x01R\x17confidenceIntervalUpper\"\xc3\x02\n" +
	"\x17ForecastClusterResponse\x12S\n" +
	"\x11cluster_forecasts\x18\x01 \x03(\v2&.apollo.forecaster.v1.ResourceForecastR\x10clusterForecasts\x12g\n" +
	"\x0enode_forecasts\x18\x02 \x03(\v2@.apollo.forecaster.v1.ForecastClusterResponse.NodeForecastsEntryR\rnodeForecasts\x1aj\n" +
	"\x12NodeForecastsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.apollo.forecaster.v1.NodeForecastResultR\x05value:\x028\x01\"z\n" +
	"\x12NodeForecastResult\x12D\n" +
	"\tforecasts\x18\x01 \x03(\v2&.apollo.forecaster.v1.ResourceForecastR\tforecasts\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\"\x8f\x02\n" +
	"\x10PeakIdleResponse\x12G\n" +
	"\fpeak_periods\x18\x01 \x03(\v2$.apollo.forecaster.v1.PeakIdlePeriodR\vpeakPeriods\x12G\n" +
	"\fidle_periods\x18\x02 \x03(\v2$.apollo.forecaster.v1.PeakIdlePeriodR\vidlePeriods\x12i\n" +
	"\x18recommended_batch_window\x18\x03 \x01(\v2/.apollo.forecaster.v1.BatchWindowRecommendationR\x16recommendedBatchWindow\"\x82\x01\n" +
	"\x0ePeakIdlePeriod\x12'\n" +
	"\x0fhorizon_minutes\x18\x01 \x01(\x05R\x0ehorizonMinutes\x12'\n" +
	"\x0favg_utilization\x18\x02 \x01(\x01R\x0eavgUtilization\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"\xae\x01\n" +
	"\x19BatchWindowRecommendation\x120\n" +
	"\x14start_offset_minutes\x18\x01 \x01(\x05R\x12startOffsetMinutes\x12,\n" +
	"\x12end_offset_minutes\x18\x02 \x01(\x05R\x10endOffsetMinutes\x121\n" +
	"\x14expected_utilization\x18\x03 \x01(\x01R\x13expectedUtilization\"d\n" +
	"\x15SubmitHistoryResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12/\n" +
	"\x13snapshots_processed\x18\x02 \x01(\x05R\x12snapshotsProcessed\"\xe1\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vmodel_ready\x18\x03 \x01(\x05R\n" +
	"modelReady\x12+\n" +
	"\x11total_predictions\x18\x04 \x01(\x03R\x10totalPredictions\x12H\n" +
	"\x12last_training_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10lastTrainingTime2\xc2\x04\n" +
	"\x1dNodeResourceForecasterService\x12n\n" +
	"\x15ForecastNodeResources\x12).apollo.forecaster.v1.ForecastNodeRequest\x1a*.apollo.forecaster.v1.ForecastNodeResponse\x12w\n" +
	"\x18ForecastClusterResources\x12,.apollo.forecaster.v1.ForecastClusterRequest\x1a-.apollo.forecaster.v1.ForecastClusterResponse\x12f\n" +
	"\x15GetPeakIdlePrediction\x12%.apollo.forecaster.v1.PeakIdleRequest\x1a&.apollo.forecaster.v1.PeakIdleResponse\x12l\n" +
	"\x11SubmitHistoryData\x12*.apollo.forecaster.v1.SubmitHistoryRequest\x1a+.apollo.forecaster.v1.SubmitHistoryResponse\x12b\n" +
	"\vHealthCheck\x12(.apollo.forecaster.v1.HealthCheckRequest\x1a).apollo.forecaster.v1.HealthCheckResponseB4Z2apollo/node-resource-forecaster/proto/forecasterpbb\x06proto3"

var (
	file_forecaster_proto_rawDescOnce sync.Once
	file_forecaster_proto_rawDescData []byte
)

func file_forecaster_proto_rawDescGZIP() []byte {
	file_forecaster_proto_rawDescOnce.Do(func() {
		file_forecaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forecaster_proto_rawDesc), len(file_forecaster_proto_rawDesc)))
	})
	return file_forecaster_proto_rawDescData
}

var file_forecaster_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_forecaster_proto_goTypes = []any{
	(*ForecastNodeRequest)(nil),       // 0: apollo.forecaster.v1.ForecastNodeRequest
	(*ForecastClusterRequest)(nil),    // 1: apollo.forecaster.v1.ForecastClusterRequest
	(*PeakIdleRequest)(nil),           // 2: apollo.forecaster.v1.PeakIdleRequest
	(*SubmitHistoryRequest)(nil),      // 3: apollo.forecaster.v1.SubmitHistoryRequest
	(*ResourceSnapshot)(nil),          // 4: apollo.forecaster.v1.ResourceSnapshot
	(*HealthCheckRequest)(nil),        // 5: apollo.forecaster.v1.HealthCheckRequest
	(*ForecastNodeResponse)(nil),      // 6: apollo.forecaster.v1.ForecastNodeResponse
	(*ResourceForecast)(nil),          // 7: apollo.forecaster.v1.ResourceForecast
	(*ForecastClusterResponse)(nil),   // 8: apollo.forecaster.v1.ForecastClusterResponse
	(*NodeForecastResult)(nil),        // 9: apollo.forecaster.v1.NodeForecastResult
	(*PeakIdleResponse)(nil),          // 10: apollo.forecaster.v1.PeakIdleResponse
	(*PeakIdlePeriod)(nil),            // 11: apollo.forecaster.v1.PeakIdlePeriod
	(*BatchWindowRecommendation)(nil), // 12: apollo.forecaster.v1.BatchWindowRecommendation
	(*SubmitHistoryResponse)(nil),     // 13: apollo.forecaster.v1.SubmitHistoryResponse
	(*HealthCheckResponse)(nil),       // 14: apollo.forecaster.v1.HealthCheckResponse
	nil,                               // 15: apollo.forecaster.v1.ForecastClusterResponse.NodeForecastsEntry
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_forecaster_proto_depIdxs = []int32{
	4,  // 0: apollo.forecaster.v1.SubmitHistoryRequest.snapshots:type_name -> apollo.forecaster.v1.ResourceSnapshot
	16, // 1: apollo.forecaster.v1.ResourceSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 2: apollo.forecaster.v1.ForecastNodeResponse.forecasts:type_name -> apollo.forecaster.v1.ResourceForecast
	7,  // 3: apollo.forecaster.v1.ForecastClusterResponse.cluster_forecasts:type_name -> apollo.forecaster.v1.ResourceForecast
	15, // 4: apollo.forecaster.v1.ForecastClusterResponse.node_forecasts:type_name -> apollo.forecaster.v1.ForecastClusterResponse.NodeForecastsEntry
	7,  // 5: apollo.forecaster.v1.NodeForecastResult.forecasts:type_name -> apollo.forecaster.v1.ResourceForecast
	11, // 6: apollo.forecaster.v1.PeakIdleResponse.peak_periods:type_name -> apollo.forecaster.v1.PeakIdlePeriod
	11, // 7: apollo.forecaster.v1.PeakIdleResponse.idle_periods:type_name -> apollo.forecaster.v1.PeakIdlePeriod
	12, // 8: apollo.forecaster.v1.PeakIdleResponse.recommended_batch_window:type_name -> apollo.forecaster.v1.BatchWindowRecommendation
	16, // 9: apollo.forecaster.v1.HealthCheckResponse.last_training_time:type_name -> google.protobuf.Timestamp
	9,  // 10: apollo.forecaster.v1.ForecastClusterResponse.NodeForecastsEntry.value:type_name -> apollo.forecaster.v1.NodeForecastResult
	0,  // 11: apollo.forecaster.v1.NodeResourceForecasterService.ForecastNodeResources:input_type -> apollo.forecaster.v1.ForecastNodeRequest
	1,  // 12: apollo.forecaster.v1.NodeResourceForecasterService.ForecastClusterResources:input_type -> apollo.forecaster.v1.ForecastClusterRequest
	2,  // 13: apollo.forecaster.v1.NodeResourceForecasterService.GetPeakIdlePrediction:input_type -> apollo.forecaster.v1.PeakIdleRequest
	3,  // 14: apollo.forecaster.v1.NodeResourceForecasterService.SubmitHistoryData:input_type -> apollo.forecaster.v1.SubmitHistoryRequest
	5,  // 15: apollo.forecaster.v1.NodeResourceForecasterService.HealthCheck:input_type -> apollo.forecaster.v1.HealthCheckRequest
	6,  // 16: apollo.forecaster.v1.NodeResourceForecasterService.ForecastNodeResources:output_type -> apollo.forecaster.v1.ForecastNodeResponse
	8,  // 17: apollo.forecaster.v1.NodeResourceForecasterService.ForecastClusterResources:output_type -> apollo.forecaster.v1.ForecastClusterResponse
	10, // 18: apollo.forecaster.v1.NodeResourceForecasterService.GetPeakIdlePrediction:output_type -> apollo.forecaster.v1.PeakIdleResponse
	13, // 19: apollo.forecaster.v1.NodeResourceForecasterService.SubmitHistoryData:output_type -> apollo.forecaster.v1.SubmitHistoryResponse
	14, // 20: apollo.forecaster.v1.NodeResourceForecasterService.HealthCheck:output_type -> apollo.forecaster.v1.HealthCheckResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_forecaster_proto_init() }
func file_forecaster_proto_init() {
	if File_forecaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forecaster_proto_rawDesc), len(file_forecaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forecaster_proto_goTypes,
		DependencyIndexes: file_forecaster_proto_depIdxs,
		MessageInfos:      file_forecaster_proto_msgTypes,
	}.Build()
	File_forecaster_proto = out.File
	file_forecaster_proto_goTypes = nil
	file_forecaster_proto_depIdxs = nil
}
