// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: forecaster.proto

package forecasterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NodeResourceForecasterService_ForecastNodeResources_FullMethodName    = "/apollo.forecaster.v1.NodeResourceForecasterService/ForecastNodeResources"
	NodeResourceForecasterService_ForecastClusterResources_FullMethodName = "/apollo.forecaster.v1.NodeResourceForecasterService/ForecastClusterResources"
	NodeResourceForecasterService_GetPeakIdlePrediction_FullMethodName    = "/apollo.forecaster.v1.NodeResourceForecasterService/GetPeakIdlePrediction"
	NodeResourceForecasterService_SubmitHistoryData_FullMethodName        = "/apollo.forecaster.v1.NodeResourceForecasterService/SubmitHistoryData"
	NodeResourceForecasterService_HealthCheck_FullMethodName              = "/apollo.forecaster.v1.NodeResourceForecasterService/HealthCheck"
)

// NodeResourceForecasterServiceClient is the client API for NodeResourceForecasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeResourceForecasterServiceClient interface {
	// 특정 노드의 리소스 사용량 예측
	ForecastNodeResources(ctx context.Context, in *ForecastNodeRequest, opts ...grpc.CallOption) (*ForecastNodeResponse, error)
	// 클러스터 전체 리소스 사용량 예측
	ForecastClusterResources(ctx context.Context, in *ForecastClusterRequest, opts ...grpc.CallOption) (*ForecastClusterResponse, error)
	// 피크/유휴 시간대 예측
	GetPeakIdlePrediction(ctx context.Context, in *PeakIdleRequest, opts ...grpc.CallOption) (*PeakIdleResponse, error)
	// 히스토리 데이터 제출 (Insight-Scope에서 호출)
	SubmitHistoryData(ctx context.Context, in *SubmitHistoryRequest, opts ...grpc.CallOption) (*SubmitHistoryResponse, error)
	// 헬스 체크
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nodeResourceForecasterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeResourceForecasterServiceClient(cc grpc.ClientConnInterface) NodeResourceForecasterServiceClient {
	return &nodeResourceForecasterServiceClient{cc}
}

func (c *nodeResourceForecasterServiceClient) ForecastNodeResources(ctx context.Context, in *ForecastNodeRequest, opts ...grpc.CallOption) (*ForecastNodeResponse, error) {
	out := new(ForecastNodeResponse)
	err := c.cc.Invoke(ctx, NodeResourceForecasterService_ForecastNodeResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeResourceForecasterServiceClient) ForecastClusterResources(ctx context.Context, in *ForecastClusterRequest, opts ...grpc.CallOption) (*ForecastClusterResponse, error) {
	out := new(ForecastClusterResponse)
	err := c.cc.Invoke(ctx, NodeResourceForecasterService_ForecastClusterResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeResourceForecasterServiceClient) GetPeakIdlePrediction(ctx context.Context, in *PeakIdleRequest, opts ...grpc.CallOption) (*PeakIdleResponse, error) {
	out := new(PeakIdleResponse)
	err := c.cc.Invoke(ctx, NodeResourceForecasterService_GetPeakIdlePrediction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeResourceForecasterServiceClient) SubmitHistoryData(ctx context.Context, in *SubmitHistoryRequest, opts ...grpc.CallOption) (*SubmitHistoryResponse, error) {
	out := new(SubmitHistoryResponse)
	err := c.cc.Invoke(ctx, NodeResourceForecasterService_SubmitHistoryData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeResourceForecasterServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NodeResourceForecasterService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeResourceForecasterServiceServer is the server API for NodeResourceForecasterService service.
// All implementations must embed UnimplementedNodeResourceForecasterServiceServer
// for forward compatibility
type NodeResourceForecasterServiceServer interface {
	// 특정 노드의 리소스 사용량 예측
	ForecastNodeResources(context.Context, *ForecastNodeRequest) (*ForecastNodeResponse, error)
	// 클러스터 전체 리소스 사용량 예측
	ForecastClusterResources(context.Context, *ForecastClusterRequest) (*ForecastClusterResponse, error)
	// 피크/유휴 시간대 예측
	GetPeakIdlePrediction(context.Context, *PeakIdleRequest) (*PeakIdleResponse, error)
	// 히스토리 데이터 제출 (Insight-Scope에서 호출)
	SubmitHistoryData(context.Context, *SubmitHistoryRequest) (*SubmitHistoryResponse, error)
	// 헬스 체크
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNodeResourceForecasterServiceServer()
}

// UnimplementedNodeResourceForecasterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeResourceForecasterServiceServer struct {
}

func (UnimplementedNodeResourceForecasterServiceServer) ForecastNodeResources(context.Context, *ForecastNodeRequest) (*ForecastNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForecastNodeResources not implemented")
}
func (UnimplementedNodeResourceForecasterServiceServer) ForecastClusterResources(context.Context, *ForecastClusterRequest) (*ForecastClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForecastClusterResources not implemented")
}
func (UnimplementedNodeResourceForecasterServiceServer) GetPeakIdlePrediction(context.Context, *PeakIdleRequest) (*PeakIdleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeakIdlePrediction not implemented")
}
func (UnimplementedNodeResourceForecasterServiceServer) SubmitHistoryData(context.Context, *SubmitHistoryRequest) (*SubmitHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitHistoryData not implemented")
}
func (UnimplementedNodeResourceForecasterServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNodeResourceForecasterServiceServer) mustEmbedUnimplementedNodeResourceForecasterServiceServer() {
}

// UnsafeNodeResourceForecasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeResourceForecasterServiceServer will
// result in compilation errors.
type UnsafeNodeResourceForecasterServiceServer interface {
	mustEmbedUnimplementedNodeResourceForecasterServiceServer()
}

func RegisterNodeResourceForecasterServiceServer(s grpc.ServiceRegistrar, srv NodeResourceForecasterServiceServer) {
	s.RegisterService(&NodeResourceForecasterService_ServiceDesc, srv)
}

func _NodeResourceForecasterService_ForecastNodeResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeResourceForecasterServiceServer).ForecastNodeResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeResourceForecasterService_ForecastNodeResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeResourceForecasterServiceServer).ForecastNodeResources(ctx, req.(*ForecastNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeResourceForecasterService_ForecastClusterResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForecastClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeResourceForecasterServiceServer).ForecastClusterResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeResourceForecasterService_ForecastClusterResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeResourceForecasterServiceServer).ForecastClusterResources(ctx, req.(*ForecastClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeResourceForecasterService_GetPeakIdlePrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeakIdleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeResourceForecasterServiceServer).GetPeakIdlePrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeResourceForecasterService_GetPeakIdlePrediction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeResourceForecasterServiceServer).GetPeakIdlePrediction(ctx, req.(*PeakIdleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeResourceForecasterService_SubmitHistoryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeResourceForecasterServiceServer).SubmitHistoryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeResourceForecasterService_SubmitHistoryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeResourceForecasterServiceServer).SubmitHistoryData(ctx, req.(*SubmitHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeResourceForecasterService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeResourceForecasterServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeResourceForecasterService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeResourceForecasterServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeResourceForecasterService_ServiceDesc is the grpc.ServiceDesc for NodeResourceForecasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeResourceForecasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.forecaster.v1.NodeResourceForecasterService",
	HandlerType: (*NodeResourceForecasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForecastNodeResources",
			Handler:    _NodeResourceForecasterService_ForecastNodeResources_Handler,
		},
		{
			MethodName: "ForecastClusterResources",
			Handler:    _NodeResourceForecasterService_ForecastClusterResources_Handler,
		},
		{
			MethodName: "GetPeakIdlePrediction",
			Handler:    _NodeResourceForecasterService_GetPeakIdlePrediction_Handler,
		},
		{
			MethodName: "SubmitHistoryData",
			Handler:    _NodeResourceForecasterService_SubmitHistoryData_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NodeResourceForecasterService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forecaster.proto",
}
